import Head from 'next/head';
import Image from 'next/image';
import Skeleton from 'react-loading-skeleton';
import FormSignup from '../modules/signup/FormSignup';

export default function Home() {
  return (
    <div className="container-home">
      <Head>
        <title>Werk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <div>
        <FormSignup/>
      </div>
    </div>
  )
}
