import React from 'react';
import Head from 'next/head';

const Header = () => {
  return (
    <>
      <Head>
        <title>Werk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
    </>
  );
}

export default Header;
