import React from 'react';
import Head from 'next/head';

interface Props {
  title?: string,
}

const Header = ({ title }: Props) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="" />
    </Head>
  );
}

export default Header;
